web:
  build: .
  command: bundle exec unicorn_rails -E production
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  ports:
    - "0.0.0.0:80:8080"
  links:
    - db
    - redis
  environment:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
    DATABASE_URL: postgresql://postgres:password@db/postgres
    IMPORT_DATABASE_URL: sqlite3:db/development.sqlite3
    SECRET_KEY_BASE: 155405921768701eefbd5e5cc310ef4832f0e7b8cb88136fc635f58673e959e24588240ff267f2abda36cd4e1bdafee4a5caebad9eeeef19dc0378d47b2d4e78
    REDIS_URL: redis://redis:6379/0
    STACK_PATH: /usr/src/app

queue:
  build: .
  command: bundle exec sidekiq -e production -c 25
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  links:
    - db
    - redis
  environment:
    RAILS_ENV: production
    DATABASE_URL: postgresql://postgres:password@db/postgres
    IMPORT_DATABASE_URL: sqlite3:db/development.sqlite3
    SECRET_KEY_BASE: 155405921768701eefbd5e5cc310ef4832f0e7b8cb88136fc635f58673e959e24588240ff267f2abda36cd4e1bdafee4a5caebad9eeeef19dc0378d47b2d4e78
    REDIS_URL: redis://redis:6379/0

db:
  image: postgres:9.4.1
  environment:
    POSTGRES_PASSWORD: password
  ports:
    - "0.0.0.0:5432:5432"

redis:
  image: redis:3.0.0
  ports:
    - "0.0.0.0:6379:6379"