source 'https://rubygems.org'

gem 'unicorn'
gem 'rails', '4.2.2'
gem 'sqlite3'
gem 'pg'

gem 'figaro'
gem 'haml'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap_form'
gem 'bootstrap-kaminari-views'
gem 'nested_form'
gem 'spinjs-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-cookie-rails'
gem 'jbuilder', '~> 2.0'
gem 'rest-client'
gem 'kaminari'
gem 'micromachine'
gem 'redis-objects'
gem 'redis-semaphore'
gem 'google-api-client', '0.8.6'
gem 'azure-directory', github: 'kioru/azure-directory'
gem 'faraday-conductivity'
gem 'rqrcode_png'
gem 'readable-token'
gem 'nexmo'
gem 'sinatra', require: nil
gem 'le'
gem 'wannabe_bool'
gem 'validates_hostname', '~> 1.0.0'
gem 'inherited_resources'

gem 'paranoia', '~> 2.0'
gem 'simple_enum'
gem 'annotate', '~> 2.6.6'
gem 'pundit'
gem 'carrierwave'
gem 'carrierwave-data-uri'
gem 'cloudinary'
gem 'sidekiq'
gem 'seedbank'

group :development, :test do
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'ffaker'
  gem 'spring-commands-rspec'
  gem 'rspec-rails', '~> 3.0'
  gem 'rspec-activemodel-mocks'
  gem 'rspec-collection_matchers'
  gem 'quiet_assets'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry-rails'
  gem 'capistrano',  '~> 3.1'
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
  gem 'capistrano-passenger'
  gem 'letter_opener'
end

group :test do
  gem 'vcr'
  gem 'webmock'
  gem 'rack_session_access'
  gem 'show_me_the_cookies'
  gem 'test_after_commit'
end