source 'https://rubygems.org'

gem 'rails', '4.2.2'
gem 'sqlite3'

gem 'pg'
gem 'haml'
gem 'sass-rails', '~> 5.0'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'bootstrap-datepicker-rails'
gem 'bootstrap_form'
gem 'bootstrap-kaminari-views'
gem 'spinjs-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jquery-cookie-rails'
gem 'jbuilder', '~> 2.0'
gem 'rest-client'
gem 'rest-client-logger'
gem 'kaminari'
gem 'micromachine'
gem 'google-api-client'
gem 'rqrcode_png'
gem 'sinatra', require: nil

gem 'paranoia', '~> 2.0'
gem 'simple_enum'
gem 'annotate', '~> 2.6.6'
gem 'pundit'
gem 'carrierwave'
gem 'carrierwave-data-uri'
gem 'cloudinary'
gem 'sidekiq'

group :development, :test do
  gem 'capybara'
  gem 'poltergeist'
  gem 'ffaker'
  gem 'factory_girl_rails'
  gem 'spring-commands-rspec'
  gem 'rspec-rails', '~> 3.0'
  gem 'rspec-collection_matchers'
  gem 'quiet_assets'
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'pry-rails'
end

group :test do
  gem 'vcr'
  gem 'webmock'
  gem 'rack_session_access'
  gem 'show_me_the_cookies'
end