development:
  url: <%= ENV['DATABASE_URL'] || 'sqlite3:db/development.sqlite3' %>

test:
  url: <%= ENV['TEST_DATABASE_URL'] || 'sqlite3:db/test.sqlite3' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'sqlite3:db/development.sqlite3' %>

import:
  url: <%= ENV['IMPORT_DATABASE_URL'] %>