development:
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  url: <%= ENV['DATABASE_URL'] %>

import:
  url: <%= ENV['IMPORT_DATABASE_URL'] %>