development:
  url: <%= ENV['DATABASE_URL'] || 'postgresql:localhost/eucportal' %>

test:
  url: <%= ENV['TEST_DATABASE_URL'] || 'postgresql:localhost/eucportal-test' %>

production:
  url: <%= ENV['DATABASE_URL'] || 'postgresql:localhost/eucportal' %>

import:
  url: <%= ENV['IMPORT_DATABASE_URL'] %>